
This is the "7-my_list" module.
===================================

>>> print(__import__('7-base_geometry').BaseGeometry.__doc__)
Geometry class with maths operations

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


>>> test = BaseGeometry
>>> test.integer_validator("my_int", 12)
>>> test.integer_validator("width", 89)

>>> test.integer_validator("age", -10)
Traceback (most recent call last):
	...
ValueError: age must be greater than 0


>>> test.integer_validator("Camila", "Cabello")
Traceback (most recent call last):
	...
TypeError: name must be an integer


>>> test.integer_validator("distance", 0)
Traceback (most recent call last):
        ...
ValueError: distance must be greater than 0


>>> test.integer_validator("distance", 1.4)
Traceback (most recent call last):
        ...
TypeError: distance must be an integer


>>> test.integer_validator("distance", (1, 2, 3))
Traceback (most recent call last):
        ...
TypeError: distance must be an integer


>>> test.integer_validator("distance", [1, 2, 3])
Traceback (most recent call last):
        ...
TypeError: distance must be an integer


>>> test.integer_validator("distance", True)
Traceback (most recent call last):
        ...
TypeError: distance must be an integer


>>> test.integer_validator("distance", {99, 4, 100})
Traceback (most recent call last):
        ...
TypeError: distance must be an integer


>>> test.integer_validator("distance", None)
Traceback (most recent call last):
        ...
TypeError: distance must be an integer


>>> test.area()
Traceback (most recent call last):
        ...
Exception: area() is not implemented


>>> test.integer_validator()
Traceback (most recent call last):
        ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'


>>> test.integer_validator("camila")
Traceback (most recent call last):
        ...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> test.integer_validator("test", 6, 64)
Traceback (most recent call last):
        ...
TypeError: integer_validator() takes 3 positional arguments but 4 were given